[package]
name = "mpdlrc"
version = "0.1.0"
authors = ["luc65r <lucas@ransan.tk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd = "*"
lrc = "0.1"
